version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  s3-deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout # Remove this line when we are ready to start building from circle ci again
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./build/
          to: 's3://feedthemonster-development'

workflows:
  s3-deploy-workflow:
    jobs:
      - s3-deploy:
          filters:
            branches:
              only:
                - develop